substack/accounts/urls.py
from django.urls import include, path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^$', views.send_to_login, name='homepage'),
    re_path(r'^login/$', views.login_screen, name='login'),
    re_path(r'^signup/$', views.create_account, name='create'),
    re_path(r'^create/$', views.create_account, name='signup'),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^profile/$', views.account_dashboard, name='dashboard')
]

htmxpatterns = [
    re_path(r'^details/$', views.show_account, name='account-home'),
    re_path(r'^details/saved/$', views.detail_snippet, name="detail-snippet"),
    re_path(r'^details/edit/$', views.edit_snippet, name='edit-snippet'),
    re_path(r'^signup/verify-email/', views.verify_email, name="verify-email")
]

urlpatterns += htmxpatterns

substack/articles/urls.py
from django.urls import include, path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    re_path(r'^$', views.articles_authors, name="authors"),
    re_path(r'^genre/$', views.articles_genre, name='genre'),
    re_path(r'^drafts/$', views.view_drafts, name='drafts'),
    re_path(r'^create/$', views.create_article, name="create"),
    re_path(r'^(?P<slug>[\w-]+)/$', views.full_article, name='full'),
    re_path(r'^edit/(?P<key>[\d]+)/$', views.update_article, name='update'),
    re_path(r'^delete/(?P<pk>[\d]+)/$', views.delete_article, name="delete"),
    re_path(r'^authors/(?P<pk>[\d]+)/$', views.authors_view, name="authors-view"),

] 

substack/substack/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.homepage, name="homepage"),
    re_path(r'^favicon\.ico$',RedirectView.as_view(url='/static/favicon/favicon.ico')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^articles/', include('articles.urls'), name="articleshomepage"),
    re_path(r'^accounts/', include('accounts.urls'), name='accountshomepage')

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

substack/articles/models.py
from fcntl import F_SEAL_SEAL
from django.db import models
import datetime
from django.forms import ValidationError
from accounts.models import SubstackUser
import re
from ckeditor.fields import RichTextFormField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Article(models.Model):
    title =         models.CharField(max_length=200)
    description =   models.CharField(max_length = 150)
    body =          RichTextUploadingField(blank = True, null=True)
    # body =          models.TextField()
    slug =          models.SlugField()
    date =          models.DateTimeField(auto_now_add = True)
    last_edited =   models.DateTimeField(auto_now = True)
    thumbnail =     models.ImageField(default='logo.png', blank = True)
    topicslist = [
        ("Business","Business"),
        ("Culinary", "Culinary"),
        ("Culture", "Culture"),
        ("Health", "Health"),
        ("Literature", "Literature"),
        ("Other", "Other"),
        ("Politics", "Politics"),
        ("Sports", "Sports"),
    ]
    topic =         models.CharField(max_length=30, null=True, blank=True, choices=topicslist)
    author =        models.ForeignKey(SubstackUser,  null=True, blank=True, on_delete=models.CASCADE)
    views =         models.IntegerField(default=0)
    is_draft =      models.BooleanField(default=False)

    REQUIRED_FIELDS = ['title',]

    def __str__(self):
        return self.title
    
    def article_snippet(self):
        wordsList = self.body.split(' ')[0:30]
        return ' '.join(wordsList) + '...'

    def MonthDayYear(self):
        months= {'01':'Jan', '02':'Feb', '03':'Mar', 
                 '04':'Apr', '05':'May', '06':'Jun', 
                 '07':'Jul', '08':'Aug', '09':'Sep', 
                 '10':'Oct', '11':'Nov', '12':'Dec'}
        mdy = self.date.strftime("%m-%d-%y").split('-')
        return f"{months[mdy[0]]} {mdy[1]}"

    def MDYdate(self):
        months= {'01':'Jan', '02':'Feb', '03':'Mar', 
                '04':'Apr', '05':'May', '06':'Jun', 
                '07':'Jul', '08':'Aug', '09':'Sep', 
                '10':'Oct', '11':'Nov', '12':'Dec'}
        mdy = self.date.strftime("%m_%d_%Y_%-I_%M_%p").split('_')
        return f"{months[mdy[0]]} {mdy[1]}, {mdy[2]}"
    
    def MDYdate_time(self):
        months= {'01':'Jan', '02':'Feb', '03':'Mar', 
                '04':'Apr', '05':'May', '06':'Jun', 
                '07':'Jul', '08':'Aug', '09':'Sep', 
                '10':'Oct', '11':'Nov', '12':'Dec'}
        mdy = self.date.strftime("%m_%d_%Y_%-I_%M_%p").split('_')
        return f"{months[mdy[0]]} {mdy[1]} at {mdy[3]}:{mdy[4]}{mdy[5]}"


    def MDYlast_edited(self):
        months= {'01':'January', '02':'February', '03':'March', 
                '04':'April', '05':'May', '06':'June', 
                '07':'July', '08':'August', '09':'September', 
                '10':'October', '11':'November', '12':'December'}
        mdy = self.last_edited.strftime("%m_%d_%Y_%-I_%M_%p").split('_')
        return f"{months[mdy[0]]} {mdy[1]} at {mdy[3]}:{mdy[4]}{mdy[5]}"

    def generate_slug(self):
        stripped = self.title.strip()
        cleanedTitle = re.sub(r"[^a-zA-Z0-9 :]+",'', stripped).split(' ')[0:7]
        cleanedSlug =  '-'.join(cleanedTitle).lower()
        number = 1
        while Article.objects.all().filter(author_id=self.author.pk).filter(slug=cleanedSlug):
                cleanedSlug += str(number)
                number +=1
        return cleanedSlug

    def create_slug_url(self):
        return f"/articles/{self.slug}/"

    def udpate_views(self):
        self.views = self.views + 1
        self.save()
        return self.views

    def shorten_desc(self):
        desc = self.description[0:100]
        return desc+'...'

substack/articles/forms.py
from django import forms
from . import models


#add form for making new articles
class CreateArticle(forms.ModelForm):
    title = forms.CharField(max_length = 200, widget = forms.Textarea(attrs = {'placeholder': 'Enter title...', 'min_length':1, 'rows':1}))
    description = forms.CharField(widget = forms.Textarea(attrs = {'placeholder': 'Write a brief description...', 'rows':'2', }))

    class Meta:
        model = models.Article
        fields = ['title', 'description', 'body', 'thumbnail', "topic" ]
        help_texts = {
                    'title': 'Please choose a unique title.',
                    }
   

substack/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import CreateArticle
from django.http import HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from accounts.models import SubstackUser


def articles_authors(request):
    articles = Article.objects.all().filter(is_draft=False).order_by("-date")
    return render(request, 'articles/article_authors.html', context = { 'articles' : articles } )


def full_article(request, slug):
    article = Article.objects.get(slug= slug)
    article.udpate_views()
    return render(request, "articles/full_article.html" , context = { 'article' : article } )


@login_required(redirect_field_name='auth_failed', login_url= 'accounts:login')
def create_article(request):
    context = {'isCreate' : True }
    if request.POST:
        form = CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            if request.POST.get('saveAsDraft'):
                form.is_draft = True
                form.save()
                return redirect('accounts:dashboard')
            elif form.generate_slug():
                form.slug = form.generate_slug()
                form.save()
                return redirect('articles:full', slug=form.slug)
            else:
                keys = list(request.POST)
                data = {}
                for key in keys:
                    data[key] = request.POST.get(key)
                form = CreateArticle(data, instance=request.user)
                context['articleForm'] = form
    else:
        articleForm = CreateArticle()
        context['articleForm'] = articleForm

    return render(request, 'articles/article_creation.html', context = context)


def articles_genre(request):
    genre = request.GET.get('genre').capitalize()
    genreArticles = Article.objects.all().filter(topic=genre).order_by("-date")
    context = {
        'genre' : genre,
        'genreArticles' : genreArticles
    }
    return render(request, 'articles/genres.html', context=context )

@login_required(redirect_field_name='auth_failed', login_url= 'accounts:login')
def update_article(request, key):
    if request.POST:
        article = Article.objects.get(pk=key)
        form = CreateArticle(request.POST, request.FILES, instance = article)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            form.save()
            print(form.generate_slug())
            if request.POST.get('saveAsDraft'):
                form.is_draft = True
                form.save()
                return redirect('accounts:dashboard')
            elif form.generate_slug():
                form.slug = form.generate_slug()
                form.is_draft = False
                form.save()
                return redirect('articles:full', slug=form.slug)
            else:
                return HttpResponseNotFound("<h2>Oops, something happened and we're not sure what...</h2>")
            
    else:
        article = Article.objects.get(pk=key)
        articleForm = CreateArticle(instance = article)
    return render(request, 'articles/article_creation.html', context = { 'articleForm' : articleForm } )

@login_required(redirect_field_name='auth_failed', login_url= 'accounts:login')
def view_drafts(request):
    drafts = Article.objects.all().filter(author = request.user).filter(is_draft = True)

    context = {
        'drafts': drafts
    }
    return render(request, 'articles/current_drafts.html', context = context)


def delete_article(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('accounts:dashboard')


def authors_view(request, pk):
    author = SubstackUser.objects.get(pk=pk)
    authorArticles = Article.objects.all().filter(author = author, is_draft = False)
    context = {
        'author' : author,
        'articles' : authorArticles,
        'isAuthorArticles' : True
    }

    return render(request, 'articles/article_authors.html', context)


def author_profile(request):
    pass

substack/articles/templates/articles/article_authors.html
{% extends 'default.html' %}
{% load static %}
{% block customcss %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endblock customcss %}
{% block title %}Substack - Articles{% endblock title %}
{% block content %}
{% include 'snippets/generalheader.html' %}

<div class="container-fluid d-flex justify-content-center">
<div class="col-4">
    {% for article in articles %}
    <div class="border-bottom rounded-3 my-3">
        <div class="lead fs-5 mb-2 mx-2"><a class="link-dark" href="{% url 'articles:full' article.slug %}">{{article.title}}</a></div>
        <div class="fs-6 fw-light lh-1 mx-2 mb-2">{{article.shorten_desc}}</div>
    <div class="d-flex justify-content-between">
        <div class="text-muted mx-2">{{article.MDYdate}}</div>
        <div class="text-muted mx-2">{{article.views}} views</div>
    </div>
    </div>
    {% endfor %}
</div>
</div>


{% include 'snippets/footer.html' %}
{% endblock content %}

substack/articles/templates/articles/article_creation.html
{% extends 'default.html' %}
{% load static %}
{% load widget_tweaks %}
{% block customcss %} 
<link rel="stylesheet" href="{% static 'styles.css' %}"> 
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="  crossorigin="anonymous"></script>
{% endblock customcss %}
{% block title %} Substack - Create
{% endblock title %}
{% block content  %}
{% include 'snippets/generalheader.html' %}

<style>
    #title {
        font-size: 50px !important;
        color: rgb(120,120,120)  !important;
        width: 100% !important;
        outline: none !important;
        overflow-y: hidden !important;
        resize:none;
    }
    
    #description {
        font-size: 20px !important;
        color: rgb(120,120,120)  !important;
        width: 100% !important;
        outline: none !important;
        overflow-y: hidden !important;
        resize:none;
    }

    #title::placeholder, #description::placeholder { 
        color: rgb(214,214,214)  !important ;
        opacity: 1; 
    }
    
    .lightbtncolor {
        background-color: #bdc2c7 !important;
        border:1px solid white !important;
    }
    
    .lightbtncolor:hover {
        background-color: #bdc2c7 !important;
        border: 1px solid #8f9294 !important;
        cursor:default !important;
    }
    
    #id_topic {
        padding: 8px 15px;
        background-color: white;
        color: #6C757D;
        border: 1px solid #bdc2c7;
        border-radius: 4px;
    }

    #id_topic:focus, 
    #id_topic:hover {
        outline:none;
        border: 1px solid #8f9294;
    }

    #id_topic option {
        background-color: white;
    }
    
    #id_topic option:hover, #id_topic option:focus {
        background-color:#bdc2c7;
    }
</style>

<div class="d-flex justify-content-center col-4 offset-4 p-5 rounded-3 mb-5 bg-body rounded">
    
    <form id='create-article-form' method='post' action="." enctype="multipart/form-data">{% csrf_token %}
        {% render_field articleForm.media %}
        {% render_field articleForm.title id="title" class="d-block border border-white lh-sm p-0 m-auto shadow-none text-start "%}
        {% render_field articleForm.description id="description" class="d-block border border-white lh-sm p-0 m-auto mt-2 shadow-none text-start" %}
        {% render_field articleForm.body id="body" %}
        
        <div class="d-flex justify-content-between mt-3">
            <div>
                {% render_field articleForm.thumbnail hidden="hidden" %} 
                <button type="button" class="btn btn-secondary lightbtncolor" id="custom-button">Upload footer image</button>
                <span id="imagepath" class="fs-6 lead text-muted ps-2">No file chosen</span>
            </div>
            
            <div class="d-block">
                <span class="fs-6 lead text-muted me-2 ps-2">Topic</span>{% render_field articleForm.topic %}
            </div>
        </div>
        <div class="d-flex justify-content-end">
            <div class="mt-5 pt-3">
                <button class="btn btn-lg btn-secondary lightbtncolor me-2 text-white" name="saveAsDraft" value="True">Draft</button>
                <button class="btn btn-lg btn-primary text-white" name="submit">Post</button>
            </div>
        </div>
    </form>

</div>

{% include 'snippets/footer.html' %}

<script>
    $(document).ready(function() {
        $('#title').on('input', function() {
            $(this)
            .width (50)
            .height(50)
            .width (this.scrollWidth)
            .height(this.scrollHeight);
        }); 
        $('#description').on('input', function() {
        $(this)
            .width (50)
            .height(50)
            .width (this.scrollWidth)
            .height(this.scrollHeight);
        }); 
        const djangoInput = document.getElementById("id_thumbnail");
        const buttonOverlay = document.getElementById("custom-button");
        const imagePath = document.getElementById("imagepath");
        buttonOverlay.addEventListener("click", function() {
            djangoInput.click();
        });
        djangoInput.addEventListener("change", function() {
            if (djangoInput.value) {
                imagePath.innerHTML = djangoInput.value.match(/[\/\\]([\w\d\s\.\-\(\)]+)$/)[1];
            } else {
                imagePath.innerHTML = "No file chosen";
            }
        });
    });
</script>
{% endblock content %}

substack/articles/templates/articles/current_drafts.html
{% extends 'default.html' %}
{% load static %}
{% block customcss %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endblock customcss %}
{% block title %}Substack - Your Drafts
{% endblock title %}
{% block content %}
{% include 'snippets/generalheader.html' %}

<div class="page">
{% for draft in drafts %}
    <div class="article"> 
        <a href="{% url 'articles:update' draft.pk %}"><h2>{{draft.title}}</h2></a>
        <h5> {{draft.author.username}}  &nbsp &nbsp &nbsp {{ draft.MonthDayYear }} </h5>
        <h6>{{ draft.description }} </h6>
    </div>
{% endfor %}
</div>


{% include 'snippets/footer.html' %}
{% endblock content %}

substack/articles/templates/articles/full_article.html
{% extends 'default.html' %}
{% load static %}
{% block customcss %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endblock customcss %}
{% block title %}Substack - {{Article.title}}
{% endblock title %}
{% block content %}
{% include 'snippets/generalheader.html' %}

<div class="container">
    <div class="row">
        <div class="col-2 border-end my-5 "></div>
        <div class="col-1 "></div>
            <div class="col-6 d-inline-block my-5">
                <p class="text-center p-0 m-0 lead fs-2">{{ article.title }}</p>
                <p class="text-black text-center">Written by: <a class="text-black text-center" href="{% url 'articles:authors-view' article.author.pk %}">{{article.author.username}}  </a></p>
                <p class="fst-italic text-muted text-center" >{{ article.description }}</p>
                <p> {{ article.body|safe}}</p>
                <div class="d-flex justify-content-center">
                    <a href="{% url 'homepage' %}"> <img class="rounded img-fluid" src="{{article.thumbnail.url}}"></a>
            </div></div>
        <div class="col-1 "></div>
        <div class="col-2 border-start my-5">
            {% if article.author.pk == request.user.pk %}
                <a href="{% url 'articles:update' article.pk %}"><button class="btn btn-sm btn-outline-secondary me-2">Edit</button></a>
                <a href="{% url 'articles:delete' article.pk %}"><button class="btn btn-sm btn-outline-danger">Delete</button><a>
            {% endif %}
        </div>
</div>
</div>

{% include 'snippets/footer.html' %}
{% endblock %}

substack/articles/templates/articles/genres.html
{% extends 'default.html' %}
{% load static %}
{% block customcss %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endblock customcss %}

{% block title %}Substack - {{genre}} Articles
{% endblock title %}
{% block content %}
{% include 'snippets/generalheader.html' %}

{% for article in genreArticles %}
    <div>
        <a href="{% url 'articles:full' slug=article.slug %}"><h2>{{article.title}}</h2></a>
        <h5> {{article.author.username}}  &nbsp &nbsp &nbsp {{ article.MonthDayYear }} </h5>
        <h6>{{ article.description }} </h6>
    </div>
{% endfor %}

{% include 'snippets/footer.html' %}
{% endblock %}