substack/accounts/urls.py
from django.urls import include, path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^$', views.send_to_login, name='homepage'),
    re_path(r'^login/$', views.login_screen, name='login'),
    re_path(r'^signup/$', views.create_account, name='create'),
    re_path(r'^create/$', views.create_account, name='signup'),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^profile/$', views.account_dashboard, name='dashboard')
]

htmxpatterns = [
    re_path(r'^details/$', views.show_account, name='account-home'),
    re_path(r'^details/saved/$', views.detail_snippet, name="detail-snippet"),
    re_path(r'^details/edit/$', views.edit_snippet, name='edit-snippet'),
    re_path(r'^signup/verify-email/', views.verify_email, name="verify-email")
]

urlpatterns += htmxpatterns

substack/articles/urls.py
from django.urls import include, path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    re_path(r'^$', views.articles_authors, name="authors"),
    re_path(r'^genre/$', views.articles_genre, name='genre'),
    re_path(r'^drafts/$', views.view_drafts, name='drafts'),
    re_path(r'^create/$', views.create_article, name="create"),
    re_path(r'^(?P<slug>[\w-]+)/$', views.full_article, name='full'),
    re_path(r'^edit/(?P<key>[\d]+)/$', views.update_article, name='update'),
    re_path(r'^delete/(?P<pk>[\d]+)/$', views.delete_article, name="delete"),
    re_path(r'^authors/(?P<pk>[\d]+)/$', views.authors_view, name="authors-view"),

] 

substack/substack/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.homepage, name="homepage"),
    re_path(r'^favicon\.ico$',RedirectView.as_view(url='/static/favicon/favicon.ico')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^articles/', include('articles.urls'), name="articleshomepage"),
    re_path(r'^accounts/', include('accounts.urls'), name='accountshomepage')

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

substack/accounts/models.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

# Create your models here.

class SubstackUserManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, password=None):
        if not email:
            raise ValueError("Users must register with an email address.")
        if not username:
            raise ValueError("Users must create a username.")
        if not first_name:
            raise ValueError("User must enter a first name")
        if not last_name:
            raise ValueError("User must enter a last name")
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, first_name, last_name, password=None):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
            password = password,
            )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class SubstackUser(AbstractBaseUser):
    
    first_name     = models.CharField(verbose_name='first name', max_length=40)
    last_name      = models.CharField(verbose_name='last name', max_length=40)
    email          = models.EmailField(verbose_name='email', max_length=60, unique=True)
    username       = models.CharField(max_length=30, unique=True)
    date_joined    = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login     = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin       = models.BooleanField(default = False)
    is_active      = models.BooleanField(default = True)
    is_staff       = models.BooleanField(default = False)
    is_superuser   = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'username',]

    objects = SubstackUserManager()

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True
    

substack/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from .models import SubstackUser
from django.forms.models import modelformset_factory, modelform_factory

class SubstackUserCreation(UserCreationForm):
    email = forms.EmailField(max_length=60, min_length = 6,
                            help_text = 'Please enter a valid email address (required).'
                            )

    class Meta:
        model = SubstackUser
        fields = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2']
    
    def clean_username(self):
        username = self.cleaned_data['username']
        if len(username) < 4:
            raise forms.ValidationError("This username is too short")
        return username
        

class SubstackAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = SubstackUser
        fields = ("email", "password")

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login, please try again")


class SubstackUpdateForm(forms.ModelForm):
    
    class Meta:
        model = SubstackUser
        fields = ('email', 'username')
    
    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            try:
                account = SubstackUser.objects.exclude(pk=self.instance.pk).get(email=email)
            except SubstackUser.DoesNotExist:
                return email
            raise forms.ValidationError('The email "%s" is already in use.' % account.email)

    def clean_username(self):
        if self.is_valid():
            username  = self.cleaned_data['username']
            try:
                account = SubstackUser.objects.exclude(pk=self.instance.pk).get(email=username)
            except SubstackUser.DoesNotExist:
                return username
            raise forms.ValidationError('The username "%s" is already in use.' % account.username)

class SubstackAccountUpdate(forms.ModelForm):
    class Meta:
        model = SubstackUser
        fields = (
            'first_name',
            'last_name',
            'email',
            'username',  
        )

SubstackAccountUpdateFormset = modelformset_factory(SubstackUser, fields = ('first_name', 'last_name', 'email', 'username' ))

substack/accounts/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout, authenticate, get_user_model
from httplib2 import Http
from .models import SubstackUser
from .forms import SubstackUserCreation, SubstackAuthenticationForm, SubstackUpdateForm, SubstackAccountUpdateFormset, SubstackAccountUpdate
from django.contrib.auth.decorators import login_required
from articles.models import Article
from articles.views import create_article

# Create your views here.
def login_screen(request):
    user = request.user
    if user.is_authenticated:
        return redirect("accounts:dashboard")

    if request.method == "POST":
        form = SubstackAuthenticationForm(request.POST)
        if form.is_valid:
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email = email, password = password)
            if user:
                login(request, user)
                if request.POST.get('auth_failed'):
                    return redirect(request.POST.get('auth_failed'))
                return redirect("accounts:dashboard")
    else:
        form = SubstackAuthenticationForm()
    return render(request, 'accounts/login_webpage.html', context = { 'form': form } )

def create_account(request):
    if request.method == 'POST':
        form = SubstackUserCreation(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:create')
    else:
        form = SubstackUserCreation()
    return render(request, 'accounts/create_account.html', context = { 'form': form } )

def logout_view(request):
    if request.user:
        logout(request)
        return redirect('homepage')
    else:
        return redirect('homepage')       

def send_to_login(request):
    return redirect('accounts:login')

@login_required(login_url='accounts:login', redirect_field_name='auth_failed')
def account_dashboard(request):
    if request.method == "POST":
        draftKey = request.POST.get('draftRedirect')
        draftData = Article.objects.get(pk=draftKey)
        return render(request, 'articles/article_creation.html', context = {'draftData' : draftData } )

    context = {}
    account = request.user #retrieve the user
    context['account'] = account 
    numArticles = len(list(Article.objects.all().filter(author = account.pk, is_draft = False)))

    if numArticles >0:
        firstArticle = Article.objects.filter(author = account.pk, is_draft=False).order_by("-date")[0]
        context['firstArticle'] = firstArticle
    else:
        context['firstArticle'] = None

    if numArticles>1:
        remainingArticles = Article.objects.filter(author = account.pk, is_draft=False).order_by("-date")[1:]
        context['remainingArticles'] = remainingArticles

    recentDrafts = Article.objects.filter(author = account.pk, is_draft=True).order_by("-date")
    context['drafts'] = recentDrafts
    context['isProfile'] = True

    return render(request, 'accounts/dashboard.html', context=context)

##Code below uses HTMX snippets         Account Updating ##
@login_required(login_url='accounts:login', redirect_field_name='auth_failed')
def show_account(request):
    pk = request.user.pk
    user = SubstackUser.objects.get(pk=pk)

    context = {
        'user' : user,
        'isDetail': True
    }
    return render(request, 'accounts/account_details.html', context)

@login_required(login_url='accounts:login', redirect_field_name='auth_failed')
def detail_snippet(request):
    pk = request.user.pk
    user = SubstackUser.objects.get(pk=pk)

    if request.method == "POST":
        form = SubstackAccountUpdate(request.POST, instance = user)
        if form.is_valid():
            form.save()
            print('form saved')
            return redirect('accounts:detail-snippet')
        else:
            return redirect('accounts:edit-snippet', user)

    form = SubstackAccountUpdate(instance=user)
    context= {
        'form' : form,
        'user' : user
    } 
    return render(request, 'accounts/snippets/detail_snippet.html', context)

@login_required(login_url='accounts:login', redirect_field_name='auth_failed')
def edit_snippet(request): 
    pk = request.user.pk
    user = SubstackUser.objects.get(pk=pk)

    form = SubstackAccountUpdate(instance=user)
    context= {
        'form' : form,
        'user' : user
    }
    return render(request, 'accounts/snippets/edit_snippet.html', context)
    
#verify if email is taken per key input
def verify_email(request): 
        email = request.POST.get('email')
        if get_user_model().objects.filter(email = email).exists():
            return HttpResponse(
                "<div id='emailverification' style='color:red;'>This email is taken!</div>"
            )
        else:
            return HttpResponse(
                "<div id='emailverification' style='color:green;'>This email is available!</div>"
            )

substack/accounts/templates/accounts/account_details.html
{% extends 'default.html' %}
{% load static %}
{% load widget_tweaks %}
{% block customcss %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endblock customcss %}
{% block title %}Substack - account management{% endblock title %}
{% block content %}
{% include 'snippets/generalheader.html' %}
<style>
    .biggerbutton {
        padding: 9px 18px; 
    }
</style>

<div id="replacement">
{% include 'accounts/snippets/detail_snippet.html' %}
</div>

{% include 'snippets/footer.html' %}
{% endblock content %}

substack/accounts/templates/accounts/create_account.html
    {% extends 'default.html' %}
    {% load static %}
    {% load widget_tweaks %}
    {% block customcss %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endblock customcss %}
    {% block title %}Substack - Create an account!
    {% endblock title %}
    {% block content %}
    {% include 'snippets/generalheader.html' %}
    {% url 'accounts:verify-email' as verify_email %}

    <div class="align-center col-4 offset-4 mt-5 p-5 pb-2 border rounded-3 shadow-lg">
        <p class="display-5 text-muted text-center fst-italic mb-2 ml-0">Create an account</p>
        <hr class="bg-dark">
        <form class="d-block" method="post" action="{% url 'accounts:create' %}">
            {% csrf_token %}
            
            <div class="form-group my-3">
                <div class="d-flex justify-content-around">

                    {% render_field form.first_name class="form-control me-2" placeholder="First name" %}
                    {{ form.first_name.errors|striptags}}
    
                    {% render_field form.last_name class="form-control" placeholder="Last name" %}
                    {{ form.last_name.errors|striptags}}
                </div> 
                {% render_field form.username class="form-control my-3" placeholder="Create a username"%}
                {{ form.username.errors|striptags }}

                {% render_field form.email class="form-control mt-3 mb-2" placeholder="Email" hx-post=verify_email hx-trigger="keyup[target.value.length > 7]" hx-target="#emailverification" hx-swap="outerHTML" %}
                {{ form.email.errors|striptags }}

                <div id="emailverification"></div>

                {% render_field form.password1 class="form-control my-3" placeholder="Password"%}
                {{ form.password1.errors|striptags }}


                {% render_field form.password2 class="form-control my-3" placeholder="Re-type password"%}
                {{ form.password2.errors|striptags}}
            </div>
            <button type="submit" class="btn btn-lg btn-primary text-white text-center mt-2 px-4 offset-5">Create</button>
        </form>
        <p class="text-muted text-center mt-3">If you already have an account, <a class="text-muted" href="{% url 'accounts:login' %}">please click here</a></p>
    </div>

{% include 'snippets/footer.html' %}
{% endblock %}

substack/accounts/templates/accounts/dashboard.html
{% extends 'default.html' %}
{% load static %}
{% block customcss %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endblock customcss %}
{% block title %}Substack Dashboard-{{account.username}}'s Newsletter{% endblock title %}
{% block content %}

{% include 'snippets/generalheader.html' %}

<style>

    a, a:visited {
        text-decoration: none !important;
    }
    a:hover {
        text-decoration: underline !important;
    }

    
</style>

<div class="container-sm my-4">
    <div class="row justify-content-center">
        <div class="col-2"></div>
        <div class="col-1 border-start"></div>
        <div class="col-5">
            <p class="display-6 fw-lighter">Posts</p>
            {% if firstArticle %}
            <div class="border rounded-3">
                <div class="lead fs-3 mx-2"><a class="link-dark " href="{% url 'articles:full' firstArticle.slug %}">{{firstArticle.title}}</a></div>&nbsp&nbsp&nbsp<small class="text-muted text-sm-end d-inline-block">{{firstArticle.MDYdate}}</small>
                <div class="border-bottom"></div>
                <div class="lead text-center fs-2">{{firstArticle.views}}</div>
                <p class="text-muted text-center my-0">Total Views</p>
            </div>

            {% for article in remainingArticles %}
            <div class="border-bottom rounded-3 my-3">
                <div class="lead fs-5 mx-2"><a class="link-dark" href="{% url 'articles:full' article.slug %}">{{article.title}}</a></div>
            <div class="d-flex justify-content-between">
                <div class="text-muted mx-2">{{article.MDYdate}}</div>
                <div class="text-muted mx-2">{{article.views}} views</div>
            </div>
            </div>
            {% endfor %}

            {% else %}
            <div class="border border-primary rounded-3">
                <div class="lead fs-3 mx-2"><a class="link-dark " href="{% url 'articles:create' %}">Create your first article</a></div>&nbsp&nbsp&nbsp
            </div>
            {% endif %}
        </div>

    <div class="col-2">
            <p class="display-6 fw-lighter mx-3">Create</p>
            <div class="mx-3"><a href="{% url 'articles:create' %}">Start Writing</a></div>
            <div class="mx-3 mt-1"><a href="{% url 'articles:create' %}">Start Thread</a></div>
            <div class="mx-3 mt-1"><a href="{% url 'articles:create' %}">New Podcast</a></div>
            <p class="display-6 fw-lighter mx-3 mt-3 px-0">Drafts</p>
            {% for draft in drafts %}
                <div class="mx-3 mt-1"><a href="{% url 'articles:update' draft.pk %}"> {{draft.title}} </a></div>
            {% endfor %}

</div>
<div class="col-2 border-start"></div>

{% include 'snippets/footer.html' %}
{% endblock content%}

substack/accounts/templates/accounts/login_webpage.html
{% extends 'default.html' %}
{% load static %}
{% load widget_tweaks %}
{% block customcss %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endblock customcss %}
{% block title %}Substack - Login
{% endblock title %}
{% block content %}
{% include 'snippets/generalheader.html' %}

<div class="d-block align-center col-4 offset-4 mt-5 border border rounded-3 shadow-lg p-3 mb-2 bg-body rounded">
    <p class="display-5 text-muted text-center fst-italic mb-2 ml-0">Welcome back!</p>
    <hr class="bg-dark">
    <form class="d-block " method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <div class="col-8 m-auto">
            {% render_field form.email class="form-control my-3" placeholder="Email"%}
            {{ form.email.errors|striptags }}

            {% render_field form.password class="form-control mt-3 mb-2" placeholder="Password" %}
            {{ form.non_field_errors|striptags }}
            <button type="submit" class="btn btn-lg btn-primary text-white text-center mt-2 px-5 offset-4    ">Login</button>
        </div>
    <p class="text-muted text-center mt-3 p-0 mb-0">If you dont have an account, <a class="text-muted" href="{% url 'accounts:create' %}">please click here</a></p>
</form>

{% endblock %}

substack/accounts/templates/accounts/profile.html
{% extends 'default.html' %}
{% load static %}
{% block customcss %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endblock customcss %}
{% block title %}Substack Dashboard-{{account.username}}'s Newsletter{% endblock title %}
{% block content %}

{% include 'snippets/generalheader.html' %}

<style>

    a, a:visited {
        text-decoration: none !important;
    }
    a:hover {
        text-decoration: underline !important;
    }

    
</style>

<div class="container-sm my-4">
    <div class="row justify-content-center">
        <div class="col-2"></div>
        <div class="col-1 border-start"></div>
        <div class="col-5">
            <p class="display-6 fw-lighter">Posts</p>
            {% if firstArticle %}
            <div class="border rounded-3">
                <div class="lead fs-3 mx-2"><a class="link-dark " href="{% url 'articles:full' firstArticle.slug %}">{{firstArticle.title}}</a></div>&nbsp&nbsp&nbsp<small class="text-muted text-sm-end d-inline-block">{{firstArticle.MDYdate}}</small>
                <div class="border-bottom"></div>
                <div class="lead text-center fs-2">{{firstArticle.views}}</div>
                <p class="text-muted text-center my-0">Total Views</p>
            </div>

            {% for article in remainingArticles %}
            <div class="border-bottom rounded-3 my-3">
                <div class="lead fs-5 mx-2"><a class="link-dark" href="{% url 'articles:full' article.slug %}">{{article.title}}</a></div>
            <div class="d-flex justify-content-between">
                <div class="text-muted mx-2">{{article.MDYdate}}</div>
                <div class="text-muted mx-2">{{article.views}} views</div>
            </div>
            </div>
            {% endfor %}

            {% else %}
            <div class="border border-primary rounded-3">
                <div class="lead fs-3 mx-2"><a class="link-dark " href="{% url 'articles:create' %}">Create your first article</a></div>&nbsp&nbsp&nbsp
            </div>
            {% endif %}
        </div>

    <div class="col-2">
            <p class="display-6 fw-lighter mx-3">Create</p>
            <div class="mx-3"><a href="{% url 'articles:create' %}">Start Writing</a></div>
            <div class="mx-3 mt-1"><a href="{% url 'articles:create' %}">Start Thread</a></div>
            <div class="mx-3 mt-1"><a href="{% url 'articles:create' %}">New Podcast</a></div>
            <p class="display-6 fw-lighter mx-3 mt-3 px-0">Drafts</p>
            {% for draft in drafts %}
                <div class="mx-3 mt-1"><a href="{% url 'articles:update' draft.pk %}"> {{draft.title}} </a></div>
            {% endfor %}

</div>
<div class="col-2 border-start"></div>

{% include 'snippets/footer.html' %}
{% endblock content%}