substack/accounts/urls.py
from django.urls import include, path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^$', views.send_to_login, name='homepage'),
    re_path(r'^login/$', views.login_screen, name='login'),
    re_path(r'^signup/$', views.create_account, name='create'),
    re_path(r'^create/$', views.create_account, name='signup'),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^profile/$', views.account_dashboard, name='dashboard')
]

htmxpatterns = [
    re_path(r'^details/$', views.show_account, name='account-home'),
    re_path(r'^details/saved/$', views.detail_snippet, name="detail-snippet"),
    re_path(r'^details/edit/$', views.edit_snippet, name='edit-snippet'),
    re_path(r'^signup/verify-email/', views.verify_email, name="verify-email")
]

urlpatterns += htmxpatterns

substack/substack/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.homepage, name="homepage"),
    re_path(r'^favicon\.ico$',RedirectView.as_view(url='/static/favicon/favicon.ico')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^articles/', include('articles.urls'), name="articleshomepage"),
    re_path(r'^accounts/', include('accounts.urls'), name='accountshomepage')

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

substack/templates/snippets/footer.html
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

substack/templates/snippets/generalheader.html
{% load static %}
<style type="text/css">
    #wholenavbar {
        background-color: rgba(0,0,0,0) !important;
        z-index: 15;
    }
    #searchbar {
        width: 35vw !important;
    }
    #searchbarinput {
        background-color: rgba(0,0,0,0) !important;
        text-color: white !important;
    }

    form-control::placeholder {
        text-color:white !important;
    }

    .custombuttonbackground {
        background-color: rgba(0,0,0,0) !important;
        border-bottom: 1px solid #FF6919 !important;
    }
    .custombuttonbackground:hover,
    .custombuttonbackground:focus {
        background-color: #FF7E3C !important;
        color:white !important;
    }

    .dropdown-menu {
        min-width: inherit !important;
    }
    .noHover{
        pointer-events: none !important;
    }
    
</style>

<nav id="wholenavbar" class="navbar navbar-expand navbar-light bg-dark">
<div class="container-fluid">
    <a class="navbar-brand" href="{% url 'homepage' %}">
        <img src="{% static 'substacklogo.png' %}" alt="Substack logo image">
    </a>

    <div class="navbar-nav mb-0 me-5">
        <a class="nav-link text-white fw-bold">Resources</a>
        <a class="nav-link text-white fw-bold">Writers</a>
        <a class="nav-link text-white fw-bold">Readers</a>
    </div>    
    <div class="navbar-nav mb-0 me-5"></div>
    <div class="navbar-nav mb-0 me-5"></div>
    <div class="navbar-nav mb-0 me-5"></div>

    {% if isProfile %}
    <div class="display-6 fst-italic lead ps-5 offset-2">{{request.user.username}}'s Newsletter</div>
    {% elif isCreate %}
    <div class="display-6 fst-italic lead ps-1 offset-3">Compose</div>
    {% elif isDetail %}
    <div class="display-6 fst-italic lead ps-5 offset-2">Edit your profile</div>
    {% elif isAuthorArticles %}
    <div class="display-6 fst-italic lead ps-5 offset-2">{{author.username}}'s Newsletter</div>
    {% endif %}

    <div class="navbar-nav ms-auto mb-2 mb-0 justify-content-between">
        {% if user.is_authenticated %}

            <form action="{% url 'accounts:dashboard' %}" method="get">
                <button class="btn btn-lg btn-outline-primary custombuttonbackground rounded-2 me-3">Dashboard</button></form>
         
            <div class="btn-group btn-group-justified ">
                <button type="button" class="btn btn-lg btn-outline-primary me-2 rounded-2 custombuttonbackground dropdown-toggle" id="timezoneDropdown" data-bs-toggle="dropdown"
                    aria-expanded="false">Profile
                </button>
                <ul class="dropdown-menu col-12" aria-labelledby="timezoneDropdown">
                    <li><form action="{% url 'accounts:account-home' %}" method='get'><button class="btn rounded-2 me-3 ">Edit profile</button></form></li>
                    <li class="border-top"><form action="{% url 'accounts:logout' %}" method='get'><button class="btn rounded-2 me-3">Logout</button></form></li>
                </ul>
            </div>


        {% else %}

            <form action="{% url 'accounts:create' %}" method="get">
                <button class=" btn btn-lg btn-outline-primary custombuttonbackground rounded-2 me-3 ">Start Writing</button></form>
         
            <form action="{% url 'accounts:login' %}" method="get"><li>
                <button class="btn btn-lg btn-outline-primary custombuttonbackground me-3 rounded-2 ">Sign in</button></form>

        {% endif %}
    </div> 
</div>

</nav>

substack/templates/snippets/headtags.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'sass/main.css' %}">
    <link rel="stylesheet" href="{% static 'styles.css'%}">
</head>

substack/templates/snippets/homepageheader.html
{% load static %}
<style type="text/css">
    #wholenavbar {
        background-color: rgba(0,0,0,0) !important;
        z-index: 15;
    }
    #searchbar {
        width: 35vw !important;
    }
    #searchbarinput {
        background-color: rgba(0,0,0,0) !important;
        text-color: white !important;
    }

    form-control::placeholder {
        text-color:white !important;
    }

    .custombuttonbackground {
        background-color: rgba(0,0,0,0) !important;
    }

    .dropdown-menu {
        min-width: inherit !important;
    }
    .noHover{
        pointer-events: none !important;
    }
    
</style>

<nav id="wholenavbar" class="navbar navbar-expand navbar-light bg-dark">
<div class="container-fluid">
    <a class="navbar-brand" href="{% url 'homepage' %}">
        <img src="{% static 'substacklogo.png' %}" alt="Substack logo image">
    </a>

    <div class="navbar-nav mb-0 me-5">
        <a class="nav-link text-white fw-bold">Resources</a>
        <a class="nav-link text-white fw-bold">Writers</a>
        <a class="nav-link text-white fw-bold">Readers</a>
    </div>    
    <div class="navbar-nav mb-0 me-5"></div>
    <div class="navbar-nav mb-0 me-5"></div>
    <div class="navbar-nav mb-0 me-5"></div>
    <form id="searchbar" class="d-flex m-auto">
        <input id="searchbarinput" style="color:white !important; background-color: rbga(0,0,0,0) !important; backdrop-filter: blur(20px); !important; border-color:white !important;" class="form-control text-white me-2" type="search" placeholder="Search for writers or publications..." aria-label="search">
        <button style="color:white !important; background-color: rbga(0,0,0,0) !important; backdrop-filter: blur(20px); !important; border-color:white !important;" class="btn btn-sm btn-outline-secondary" type="submit">Search</button>
    </form>

    <div class="navbar-nav ms-auto mb-2 mb-0 justify-content-between">
        {% if user.is_authenticated %}

            <form action="{% url 'accounts:dashboard' %}" method="get">
                <button style="color:white !important; background-color: rbga(0,0,0,0) !important; backdrop-filter: blur(20px); !important; border-color:white !important;" class="btn btn-lg btn-outline-primary me-3 rounded-2 custombuttonbackground">Dashboard</button></form>
         
            <div class="btn-group btn-group-justified ">
                <button style="color:white !important; background-color: rbga(0,0,0,0) !important; backdrop-filter: blur(20px); !important; border-color:white !important;" type="button" class="btn btn-lg btn-outline-primary me-2 rounded-2 custombuttonbackground dropdown-toggle" id="timezoneDropdown" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Profile
                </button>
                <ul class="dropdown-menu col-12" aria-labelledby="timezoneDropdown">
                    <li><form action="{% url 'accounts:account-home' %}" method='get'><button class="btn dropdown-item ustombuttonbackground">Edit profile</button></form></li>
                    <li><form action="{% url 'accounts:logout' %}" method='get'><button class="btn dropdown-item border-top custombuttonbackground">Logout</button></form></li>
                </ul>
            </div>


        {% else %}

            <form action="{% url 'accounts:create' %}" method="get">
                <button style="color:white !important; background-color: rbga(0,0,0,0) !important; backdrop-filter: blur(20px); !important; border-color:white !important;" class=" btn btn-lg btn-outline-primary rounded-2 me-3 custombuttonbackground">Start Writing</button></form>
         
            <form action="{% url 'accounts:login' %}" method="get"><li>
                <button style="color:white !important; background-color: rbga(0,0,0,0) !important; backdrop-filter: blur(20px); !important; border-color:white !important;" class="btn btn-lg btn-outline-primary me-3 rounded-2 custombuttonbackground">Sign in</button></form>

        {% endif %}
    </div> 
</div>

</nav>